---
# Run this commands to get make a diff of settings
#   gsettings list-recursively > original.txt
#   diff <(cat original.txt) <(gsettings list-recursively)

# - name: Install Unity tweak tool
#   apt: pkg=unity-tweak-tool state=latest update_cache=yes cache_valid_time={{ aptcachetime }}

- name: Set workspaces preferences
  command: "{{ item }}"
  loop:
    - gsettings set org.gnome.desktop.wm.preferences num-workspaces 4

- name: Set Nautilus preferences
  command: "{{ item }}"
  loop:
    - gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
    # - gsettings set org.gnome.nautilus.icon-view default-zoom-level 'smaller'
    # - gsettings set org.gnome.nautilus.list-view default-zoom-level 'smaller'
    - gsettings set org.gnome.nautilus.list-view use-tree-view true
    # - gsettings set org.gnome.nautilus.preferences thumbnail-limit "uint64 5242880"
    # - gsettings set org.gnome.nautilus.icon-view thumbnail-size 64

- name: Set Gedit preferences
  command: "{{ item }}"
  loop:
    - gsettings set org.gnome.gedit.preferences.editor bracket-matching true
    - gsettings set org.gnome.gedit.preferences.editor create-backup-copy false
    - gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
    - gsettings set org.gnome.gedit.preferences.editor editor-font 'Hack 10'
    - gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
    - gsettings set org.gnome.gedit.preferences.editor insert-spaces true
    - gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'
    - gsettings set org.gnome.gedit.preferences.editor tabs-size "uint32 4"
    - gsettings set org.gnome.gedit.preferences.editor use-default-font false
    - gsettings set org.gnome.gedit.preferences.editor wrap-mode 'none'

- name: Set Terminal preferences
  command: "{{ item }}"
  loop:
    - gsettings set org.gnome.Terminal.Legacy.Settings new-terminal-mode 'tab'
    - gsettings set org.gnome.Terminal.Legacy.Settings tab-position 'top'
    # - gsettings set org.gnome.Terminal.Legacy.Settings encodings "['UTF-8']"
    - gsettings set org.gnome.Terminal.Legacy.Settings shortcuts-enabled true
    - gsettings set org.gnome.Terminal.Legacy.Settings tab-policy 'automatic'


