---

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", repo: "ppa:remmina-ppa-team/remmina-next" }

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "remmina" }
    - { state: "latest", name: "remmina-plugin-rdp" }
    - { state: "latest", name: "remmina-plugin-secret" }
    - { state: "latest", name: "remmina-plugin-vnc" }

