---

- name: is installed
  become: no
  stat:
      path: '{{ ansible_env.HOME }}/.sdkman'
  register: is_installed

- name: wget
  get_url:
    url: "https://get.sdkman.io"
    dest: "/tmp/download-sdkman.sh"
    mode: "a+x"
  when: is_installed.stat.exists == 0

- name: shell
  shell: '/tmp/download-sdkman.sh'
  become: no
  args:
    chdir: "{{ ansible_env.HOME }}"
    executable: /bin/bash
  when: is_installed.stat.exists == 0

- name: install
  file:
    path: /tmp/download-sdkman.sh
    state: absent
  when: is_installed.stat.exists == 0

- name: sdkman install
  become_user: "{{ ansible_env.USER }}"
  command: bash -lc "[[ -x '$(command -v {{ item.command }})' ]] || (source '/home/{{ ansible_env.USER }}/.sdkman/bin/sdkman-init.sh' && sdk i {{ item.name }})"
  loop:
    - { name: "maven", command: "mvn" }
    - { name: "gradle", command: "gradle" }
    - { name: "groovy", command: "groovy" }
    - { name: "kotlin", command: "kotlin" }
    
# - name: Install SDKMAN
#   include_role:
#     name: Comcast.sdkman
#   vars:
#     sdkman_dir: /usr/local/sdkman
#     sdkman_user: root
#     sdkman_group: root
#     sdkman_auto_answer: true
#     sdkman_update: true
#     sdkman_install_packages:
#       - { candidate: gradle, version: 4.8.1 }
#       - { candidate: groovy, version: 2.5.0 }
#       - { candidate: maven, version: 3.5.3 }
#       - { candidate: springboot, version: 2.0.2.RELEASE }
#     sdkman_flush_caches_before:
#       - temp
#     sdkman_flush_caches_after:
#       - archives
#       - broadcast
#       - candidates
#       - temp

- name: update .bashrc
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - sdkman"
    dest: "/home/{{ ansible_env.USER }}/.bashrc"
    backup: yes
    block: |
      export SDKMAN_DIR=$HOME/.sdkman
      [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
    state: present

