---

# https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
- name: apt-key add
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", repo: "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/{{ mongodb.version }} multiverse" }

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "mongodb-org" }

