---

# https://gist.github.com/komuW/b3b5d24977d4df7bd549
# - name: Installing nvm
#   shell: >
#     curl {{ nvm.repository }} | sh
#     creates={{ ansible_env.HOME }}/.nvm/nvm.sh
- name: is installed
  stat:
      path: $HOME/.nvm/nvm.sh
  register: is_installed

- name: wget
  get_url:
    url: "{{ nvm.repository }}"
    dest: "/tmp/download-nvm.sh"
    mode: "a+x"
  when: is_installed.stat.exists == 0

- name: install
  shell: '/tmp/download-nvm.sh'
  become: no
  args:
    chdir: "{{ ansible_env.HOME }}"
    executable: /bin/bash
  when: is_installed.stat.exists == 0

- name: cleanup
  file:
    path: /tmp/download-nvm.sh
    state: absent
  when: is_installed.stat.exists == 0

- name: update .bashrc
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - nvm"
    dest: "/home/{{ ansible_env.USER }}/.bashrc"
    backup: yes
    block: |
      export NVM_DIR=$HOME/.nvm
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    state: present

