- name: pip install
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default(None) or omit }}"
    version: "{{ item.version | default(None) or omit }}"
    extra_args: "{{ item.extra_args | default(None) or omit }}"
    executable: "pip3"
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  with_items:
    - { state: "latest", name: "awscli" }
    - { state: "latest", name: "aws-shell" }

- name: create ~/.aws directory
  become: no
  file: path="{{ ansible_env.HOME }}/.aws/cli" state=directory 

- name: install awscli-aliases
  become: no
  get_url: url="https://raw.githubusercontent.com/awslabs/awscli-aliases/master/alias" dest="{{ ansible_env.HOME }}/.aws/cli/alias"
    
- name: update .bashrc
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - awscli"
    dest: "/home/{{ ansible_env.USER }}/.bashrc"
    backup: yes
    block: |
      [[ -s "/usr/local/bin/aws_completer" ]] && complete -C "/usr/local/bin/aws_completer" aws
    state: present

