---

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", repo: "ppa:linuxuprising/java" }

# - name: accept license
#   debconf: name='oracle-java14-installer' question='shared/accepted-oracle-license-v1-2' value='true' vtype='select'

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "oracle-java14-installer" }
    - { state: "latest", name: "oracle-java14-set-default" }

# Fix mvn error - java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be
#    non-empty
# https://stackoverflow.com/a/50688351
- name: remove cacerts
  file: path='/etc/ssl/certs/java/cacerts' state=absent

- name: update cacerts
  shell: /usr/sbin/update-ca-certificates -f
