---

- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java 8 Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

# https://www.linuxuprising.com/2018/04/install-oracle-java-10-in-ubuntu-or.html
- name: Add Oracle Java 10 Repository
  become: yes
  apt_repository: repo='ppa:linuxuprising/java'

- name: Update apt cache
  become: yes
  apt: update_cache=true

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=present
  with_items:
    - oracle-java8-installer
    # - ca-certificates
    # - oracle-java8-set-default

- name: Install Oracle Java 10
  become: yes
  apt: name={{item}} state=present
  with_items:
    - oracle-java10-installer
    # - ca-certificates
    # - oracle-java10-set-default

# Fix mvn error - java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be
#    non-empty
# https://stackoverflow.com/a/50688351
- name: Remove cacerts
  become: yes
  file: path='/etc/ssl/certs/java/cacerts' state=absent

- name: Update cacerts index for java
  become: yes
  shell: /usr/sbin/update-ca-certificates -f
