---

- name: apt-key add
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" }

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", repo: "{{ 'deb https://deb.nodesource.com/node_' + nodejs.version + ' ' + ansible_distribution_release + ' main' }}" }

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "nodejs" }

- name: npm install
  npm:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    global: "yes"
    unsafe_perm: "yes"
  with_items:
    - { state: "latest", name: "eslint" }
    - { state: "latest", name: "gulp-cli" }
    - { state: "latest", name: "node-sass" }
    - { state: "latest", name: "prettier" }
    - { state: "latest", name: "stylelint" }
