---

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "nautilus-compare" }
    - { state: "latest", name: "nautilus-wipe" }

