---

# - name: Config MariaDb
#   include_role:
#     name: debops.mariadb
#   vars:
#     mariadb__port: "{ mariadb.port }}"
#     mariadb__upstream_version: '10.3'
#     mysql_db:
#       name: 'dbTest'
#       state: 'present'
#     # delegate_to: '{{ ansible_local.mariadb.delegate_to }}'
#     # register: application__register_database
#     mysql_user:
#       name: '{{ application__database_user }}'
#       host: '{{ ansible_local.mariadb.host }}'
#       password: '{{ application__database_password }}'
#       priv: '{{ application__database_name }}.*:ALL'
#       state: 'present'
#     # delegate_to: '{{ ansible_local.mariadb.delegate_to }}'

# https://downloads.mariadb.org/mariadb/repositories/#mirror=jaleco&distro=Ubuntu&distro_release=bionic--ubuntu_bionic&version=10.3
- name: Installing apt-key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xF1656F24C74CD1D8"

- name: Add MaraDB deb-src repository
  apt_repository: repo='deb-src http://mirror.jaleco.com/mariadb/repo/10.3/ubuntu {{ ansible_distribution_release }} main' state=present

- name: Configure MariaDB Installation
  debconf:
    name: mariadb-server
    question: "{{ item }}"
    vtype: password
    value: "Password1!"
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again
  register: configure_install

- name: Install MariaDB server
  apt: pkg=mariadb-server state=latest update_cache=yes
  when: configure_install is success
  register: install_mariadb 

- name: Install MariaDB client
  apt: pkg=mariadb-client state=latest update_cache=yes
  
- name: " {{ mariadb.port_enabled | ternary('Allow','Deny') }} port access {{ mariadb.port }}"
  ufw:
    rule: "{{ mariadb.port_enabled | ternary('allow','deny') }}"
    port: "{{ mariadb.port }}"
