---

# https://computingforgeeks.com/how-to-install-mariadb-on-ubuntu/
- name: apt-key add
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xF1656F24C74CD1D8"

- name: add-apt-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", repo: "deb [arch=amd64,arm64,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu {{ ansible_distribution_release }} main" }

- name: debconf-set-selections
  debconf:
    name: "{{ item.name }}"
    vtype: "{{ item.vtype }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
  with_items:
    - { name: "mariadb-server-10.4", vtype: "password", question: "mysql-server/root_password", value: "" }
    - { name: "mariadb-server-10.4", vtype: "password", question: "mysql-server/root_password_again", value: "" }
  changed_when: false

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "mariadb-client-10.4" }
    - { state: "latest", name: "mariadb-server-10.4" }

- name: start service
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - { name: "mariadb", state: "started", enabled: "no" }
  register: start_service_result

- name: disable mysqsl anonymous access
  shell: |
    mysql -NBe "DELETE FROM mysql.user WHERE User = ''"
  when:
    - start_service_result.results[0].state == "started"
  register: disable_anonymous_access_result
  changed_when: disable_anonymous_access_result is not succeeded
  ignore_errors: yes

- name: disable mysql root remote access
  shell: |
    mysql -NBe "DELETE FROM mysql.user WHERE User = 'root' AND Host <> 'localhost'"
  when:
    - start_service_result.results[0].state == "started"
  register: disable_root_remote_access_result
  changed_when: disable_root_remote_access_result is not succeeded
  ignore_errors: yes

- name: bugfix permission /usr/lib/mysql/plugin/auth_pam_tool_dir
  shell: |
    chmod 0755 /usr/lib/mysql/plugin/auth_pam_tool_dir
    chmod 4755 /usr/lib/mysql/plugin/auth_pam_tool_dir/*
  register: result
  changed_when: result is not succeeded

- name: "{{ mariadb.port_enabled | ternary('allow','deny') }} port access {{ mariadb.port }}"
  ufw:
    rule: "{{ mariadb.port_enabled | ternary('allow','deny') }}"
    port: "{{ mariadb.port }}"

- name: "{{ mariadb.start | ternary('started','stopped') }} service"
  service:
    name: mariadb
    state: "{{ mariadb.start | ternary('restarted','stopped') }}"
    enabled: "{{ mariadb.service_enabled }}"
