---

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", name: "snapd" }

- name: snap install
  snap:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    classic: "{{ item.classic | default('yes') }}"
  with_items:
    - { state: "present", name: "intellij-idea-ultimate" }
    - { state: "present", name: "notepadqq" }
    - { state: "present", name: "slack" }

