---

- name: pip install
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default(None) or omit }}"
    version: "{{ item.version | default(None) or omit }}"
    extra_args: "{{ item.extra_args | default(None) or omit }}"
    executable: "pip3"
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  with_items:
    - { state: "latest", name: "mitmproxy" }

- name: " {{ mitmproxy.port_enabled | ternary('allow','deny') }} port access"
  ufw:
    rule: "{{ mitmproxy.port_enabled | ternary('allow','deny') }}"
    port: "8080"

