---

- name: Install python3-pip package
  action: apt pkg=python3-pip state=present

- name: Install mitmproxy
  pip:
    name: mitmproxy
    state: present
    executable: pip3

- name: Open port 8080
  ufw:
    rule: allow
    port: 8080
