---

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "absent", repo: "ppa:certbot/certbot" }

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "absent", name: "python-certbot-apache" }

- name: pip install
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default(None) or omit }}"
    version: "{{ item.version | default(None) or omit }}"
    extra_args: "{{ item.extra_args | default(None) or omit }}"
    executable: "pip3"
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  with_items:
    - { state: "latest", name: "certbot" }
#    - { state: "latest", name: "certbot-apache" }

