---

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", repo: "ppa:kelleyk/emacs" }

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "emacs26" }

