---

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "terminator" }

- name: config directory
  file:
    path: ~/.config/terminator
    state: directory
  become: no

- name: copy config
  copy:
    src: config
    dest: ~/.config/terminator/config
  become: no
