---

- name: Install Terminator
  apt: name=terminator state=present

- name: Ensure Terminator config directory exist
  file:
    path: ~/.config/terminator
    state: directory
  become: no

- name: Copy Terminator config
  copy:
    src: config
    dest: ~/.config/terminator/config
  become: no
