---

# https://www.scootersoftware.com/download.php?zz=kb_linux_install
- name: wget
  get_url:
    url: "{{ bcompare.repository }}"
    dest: "{{ bcompare.temp_file }}"

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "gdebi-core" }

- name: install
  command: "{{ 'gdebi ' + bcompare.temp_file + ' -n' }}"

- name: cleanup
  file:
    path: "{{ bcompare.temp_file }}"
    state: absent

