---
- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "hunspell-en-us" }
    - { state: "latest", name: "language-pack-en" }
    - { state: "latest", name: "language-pack-gnome-en" }
    - { state: "latest", name: "language-pack-gnome-ja" }
    - { state: "latest", name: "language-pack-gnome-ko" }
    - { state: "latest", name: "language-pack-gnome-zh-hans" }
    - { state: "latest", name: "language-pack-gnome-zh-hant" }
    - { state: "latest", name: "language-pack-ja" }
    - { state: "latest", name: "language-pack-ko" }
    - { state: "latest", name: "language-pack-zh-hans" }
    - { state: "latest", name: "language-pack-zh-hant" }

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "ibus" }
    - { state: "absent", name: "ibus-chewing" }
    - { state: "absent", name: "ibus-hangul" }
    - { state: "absent", name: "ibus-mozc" }
    - { state: "latest", name: "ibus-sunpinyin" }
    - { state: "latest", name: "ibus-table" }
    - { state: "absent", name: "ibus-table-cangjie3" }
    - { state: "latest", name: "ibus-table-cangjie5" }
    - { state: "latest", name: "ibus-table-cantonhk" }
    - { state: "latest", name: "ibus-table-cantonese" }
    - { state: "latest", name: "ibus-table-emoji" }
    - { state: "absent", name: "ibus-table-quick-classic" }
    - { state: "latest", name: "ibus-table-quick5" }
    - { state: "absent", name: "ibus-table-wubi" }
