- name: Install Ubuntu Make Repo
  become: yes
  apt_repository:
    repo: ppa:ubuntu-desktop/ubuntu-make

- name: Install umake
  become: yes
  apt:
    name: ubuntu-make
    state: present
    update_cache: no

# TODO: Make idempotent
- name: Install IDE
  become_user: "{{ ansible_env.USER }}"
  command: bash -lc "umake ide {{ item.name }} {{ item.param }} '{{ ansible_env.HOME }}/.local/share/umake/ide/{{ item.name }}'"
  loop:
    - { name: "spring-tools-suite", param: "" }
    - { name: "idea-ultimate", param: "" }
    - { name: "datagrip", param: "" }
    - { name: "eclipse-jee", param: "" }
# Use visual studio code
#    - { name: "visual-studio-code", param: "--accept-license" }
