---

- name: apt install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "memcached" }

- name: "{{ memcached.start | ternary('started','stopped') }} service"
  service:
    name: memcached
    state: "{{ memcached.start | ternary('restarted','stopped') }}"
    enabled: "{{ memcached.service_enabled }}"
