---

- name: Install Terminator
  apt: name=terminator state=present

- name: Ensure local font directory exist
  file:
    path: ~/.local/share/fonts
    # ~/.fonts is deprecated
    # path: ~/fonts
    state: directory
  become: no

# https://github.com/adobe-fonts/source-code-pro 
# https://github.com/adobe-fonts/source-code-pro/issues/17#issuecomment-8967116 
- name: Down Source Code Pro font
  become: false
  get_url:
    url: "https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/{{ item }}"
    dest: "~/.local/share/fonts/{{ item }}"
  with_items:
    - SourceCodeVariable-Italic.otf 
    - SourceCodeVariable-Roman.otf
  
- name: Update font cache
  shell: fc-cache -fv
